apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure-config
  namespace: external-dns
type: Opaque
stringData:
  azure.json: |
    {
      "subscriptionId": {{ index .Values "external-dns" "azure" "subscriptionId" | default "" | quote }},
      "resourceGroup": {{ index .Values "external-dns" "azure" "resourceGroup" | default "" | quote }},
      "tenantId": {{ index .Values "external-dns" "azure" "tenantId" | default "" | quote }},
      "useWorkloadIdentityExtension": true
    }
