cert-manager:
  crds:
    enabled: true

defaultAcmeIssuer:
  enabled: true
  name: letsencrypt
  email: "devops@example.com"
  server: "https://acme-v02.api.letsencrypt.org/directory"
  ingressClassName: "traefik"
