infra-services:
  adp_agent_enabled: false
  aks_cluster_fqdn: joncn6653g-t94u7dbc.hcp.swedencentral.azmk8s.io
  aks_cluster_id: /subscriptions/f7f8b016-64ca-4d42-afad-de91b2eae685/resourceGroups/rg-aks-dev-swedencentral/providers/Microsoft.ContainerService/managedClusters/aks-contoso-dev-swedencentral
  aks_cluster_name: aks-contoso-dev-swedencentral
  aks_cluster_version: '1.36'
  aks_controlplane_identity_client_id: e158f36b-820d-4d06-b2fb-d3d4169f0503
  aks_controlplane_identity_id: /subscriptions/f7f8b016-64ca-4d42-afad-de91b2eae685/resourceGroups/rg-aks-dev-swedencentral/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-aks-controlplane-dev-swedencentral
  aks_kubelet_identity_client_id: f528ed2d-c183-45e3-a75b-d8dea8f96d37
  aks_oidc_issuer_url: https://swedencentral.oic.prod-aks.azure.com/35e55793-1d03-4bb1-99a3-4888c2cda0e0/19b029cf-eaec-4e13-a0bd-331fb98a0334/
  aks_outbound_type: loadBalancer
  aks_private_cluster: false
  aks_private_dns_zone_id: /subscriptions/f7f8b016-64ca-4d42-afad-de91b2eae685/resourceGroups/rg-network-dev-swedencentral/providers/Microsoft.Network/privateDnsZones/contoso.privatelink.swedencentral.azmk8s.io
  applications_destination_repo: ''
  applications_template_repo: ''
  applications_template_repo_branch: main
  az_subscription_id: f7f8b016-64ca-4d42-afad-de91b2eae685
  azure_subscription_id: f7f8b016-64ca-4d42-afad-de91b2eae685
  azure_tenant_id: 35e55793-1d03-4bb1-99a3-4888c2cda0e0
  backstage_enabled: false
  budget_enabled: false
  cloud: azure
  dns_client_id: ''
  dns_main_domain: contoso.itgix.eu
  dns_private_zone: adp.csiliev.eu
  dns_provider: azure-dns
  dns_resource_group: rg-network-dev-swedencentral
  enable_cert_manager: true
  enable_devlake: false
  enable_eso: false
  enable_falco: false
  enable_fluent_bit: false
  enable_kyverno: false
  enable_kyverno_policies: false
  enable_loki: true
  enable_policy_reporter: false
  enable_prometheus_stack: true
  enable_tempo: false
  enable_trivy_operator: true
  enable_vpa: false
  enabled_metrics_server: true
  env_git_repo: git@github.com:itgix/adp-az-tfinfra-demo.git
  env_template_repo: git@github.com:itgix/adp-tf-envtemplate-standard-az.git
  env_template_repo_branch: develop
  environment: dev
  external_dns_enabled: true
  external_secrets_enabled: false
  gitops_destination_repo: https://github.com/itgix/adp-az-client-argo-demo.git
  gitops_template_repo: git@github.com:itgix/adp-argo-az-repo.git
  gitops_template_repo_branch: feature/adapt-helm-apps-for-azure
  project_name: contoso
  provision_aks: true
  provision_identities: true
  provision_kubelet_identity: true
  provision_vnet: false
  region: swedencentral
  region_short: sc
  resource_group_id: /subscriptions/f7f8b016-64ca-4d42-afad-de91b2eae685/resourceGroups/rg-aks-dev-swedencentral
  resource_group_name: rg-aks-dev-swedencentral
  subnet_aks_apiserver_cidr: 10.10.2.0/28
  subnet_aks_apiserver_id: /subscriptions/f7f8b016-64ca-4d42-afad-de91b2eae685/resourceGroups/rg-network-dev-swedencentral/providers/Microsoft.Network/virtualNetworks/vnet-dev-swedencentral/subnets/snet-aks-apiserver-dev-swedencentral
  subnet_aks_nodes_cidr: 10.10.1.0/24
  subnet_aks_nodes_id: /subscriptions/f7f8b016-64ca-4d42-afad-de91b2eae685/resourceGroups/rg-network-dev-swedencentral/providers/Microsoft.Network/virtualNetworks/vnet-dev-swedencentral/subnets/snet-aks-nodes-dev-swedencentral
  terraform_ver: 1.15.8
  vnet_id: /subscriptions/f7f8b016-64ca-4d42-afad-de91b2eae685/resourceGroups/rg-network-dev-swedencentral/providers/Microsoft.Network/virtualNetworks/vnet-dev-swedencentral
  workload_dns_identity_client_id: af86ac7d-d661-4372-98c3-988d360b9ba1
  workload_eso_identity_client_id: cec49060-c0be-4fcb-9bd8-e4481ab117aa
  workload_private_dns_zone_ids: {}
  workload_public_dns_zone_ids: {}
