kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:itgix/adp-az-client-argo-demo.git"
    targetRevision: HEAD
    path: helm/argo-cd
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd