apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-azure-storage
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-azure
    kind: ClusterSecretStore
  target:
    name: loki-azure-storage
    creationPolicy: Owner
  data:
    - secretKey: accountKey
      remoteRef:
        key: loki-azure-storage-key