apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-azure
  # Keeping this mapped directly to the operator namespace defined in your subject pattern
  namespace: external-secrets-operator
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      # Points directly to your Sweden Central instance derived from your key_vault_id
      vaultUrl: "https://kv-contoso-dev-sc.vault.azure.net"
      serviceAccountRef:
        name: external-secrets-operator-sa
        namespace: external-secrets-operator