apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ index .Values "infra-services" "workload_eso_identity_client_id" | default "" | quote }}
    azure.workload.identity/tenant-id: {{ index .Values "infra-services" "azure_tenant_id" | default "" | quote }}
  labels:
    azure.workload.identity/use: "true"
  name: external-secrets-operator-sa
  namespace: external-secrets-operator
